"""
Part 3 - Constrained decoding.

A `LogitsProcessor` that allows only a fixed set of token ids to be generated by
masking every other token's logit to -inf before sampling. The allowed set is the
Hebrew-allowed set from identify_hebrew_tokens.py, plus the EOS token (added here
so generation can stop) and optionally the pad token.

Usage (programmatic):
    from src.part3_decoding.constrained_decode import build_processor
    lp = build_processor(tokenizer, allowed_ids)        # LogitsProcessorList
    model.generate(..., logits_processor=lp)
"""

from __future__ import annotations

import json
from pathlib import Path


def load_allowed_ids(json_path: str | Path) -> list[int]:
    data = json.loads(Path(json_path).read_text(encoding="utf-8"))
    return list(data["allowed_token_ids"])


def build_processor(tokenizer, allowed_ids, allow_eos: bool = True):
    """Return a LogitsProcessorList that permits only `allowed_ids` (+ EOS)."""
    import torch
    from transformers import LogitsProcessor, LogitsProcessorList

    allowed = {int(i) for i in allowed_ids}
    if allow_eos and tokenizer.eos_token_id is not None:
        allowed.add(int(tokenizer.eos_token_id))
    if tokenizer.pad_token_id is not None:
        allowed.add(int(tokenizer.pad_token_id))

    vocab = len(tokenizer)
    mask = torch.ones(vocab, dtype=torch.bool)  # True = blocked
    idx = torch.tensor([i for i in allowed if i < vocab], dtype=torch.long)
    mask[idx] = False

    class AllowedTokensOnly(LogitsProcessor):
        def __init__(self, blocked_mask):
            self.blocked = blocked_mask

        def __call__(self, input_ids, scores):
            blocked = self.blocked
            # Model vocab may be padded above len(tokenizer) for hardware efficiency
            # (e.g. Qwen2.5: tokenizer=151,665 but logits=152,064). Treat the extra
            # tail ids as blocked so the mask matches the logit width.
            if blocked.shape[0] != scores.shape[-1]:
                resized = torch.ones(scores.shape[-1], dtype=torch.bool)
                resized[: blocked.shape[0]] = blocked
                blocked = resized
                self.blocked = blocked
            blocked = blocked.to(scores.device)
            scores = scores.masked_fill(blocked.unsqueeze(0), float("-inf"))
            return scores

    return LogitsProcessorList([AllowedTokensOnly(mask)])


if __name__ == "__main__":
    # Lightweight structural self-test (no model load): verifies the mask logic
    # with a fake tokenizer-like object and a torch tensor, if torch is present.
    try:
        import torch

        class _FakeTok:
            eos_token_id = 2
            pad_token_id = None

            def __len__(self):
                return 10

        lp = build_processor(_FakeTok(), [3, 4, 5])
        scores = torch.zeros(1, 10)
        out = lp[0](torch.zeros(1, 1, dtype=torch.long), scores.clone())
        allowed = (out[0] != float("-inf")).nonzero().flatten().tolist()
        print("allowed after mask:", allowed, "(expected [2, 3, 4, 5])")
    except ImportError:
        print("torch not installed; self-test skipped (logic is unchanged).")
